INFLUXDB:
  HOST: 172.30.1.140
  PORT: 8086
  USER: influx
  PASSWORD: influx
  DB_NAME: telegraf

MARIADB:
  HOST: 172.30.1.140
  PORT: 3306
  USER: root
  PASSWORD: root
  DB_NAME: metric_watcher

POSTGRESQLDB:
  HOST: 172.30.1.140
  PORT: 5432
  USER: prefect
  PASSWORD: prefect
  DB_NAME: prefect
