INFLUXDB:
  HOST: 172.30.1.170
  PORT: 8086
  USER: influx
  PASSWORD: influx
  DB_NAME: metric_watcher

MARIADB:
  HOST: 172.30.1.170
  PORT: 3306
  USER: root
  PASSWORD: root
  DB_NAME: metric_watcher